-- Migracion: puebla_perfil_recomendado_de_productos. Idempotente.
--
-- productos.perfil_recomendado (columna agregada en 20260917_000002) es una referencia
-- interna para el vendedor/encargado y para Alex: a que tipo de cliente se le puede
-- sugerir cada producto (mujeres, hombres, ninos, adultos mayores, deportistas, mascotas)
-- y, cuando aplica, advertencia de embarazo/lactancia. No se muestra tal cual al cliente,
-- es solo para orientar la conversacion -- igual que productos.beneficios.
--
-- Redactado a mano para los 233 productos reales (se excluyen id_producto 200 y 202,
-- que no son productos). Confirmado que QA y produccion comparten catalogo 1:1 por
-- id_producto.
--
-- Cada UPDATE esta guardado con "WHERE perfil_recomendado IS NULL OR perfil_recomendado = ''"
-- para nunca sobrescribir un valor que ya exista.

UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 1 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 2 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 3 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 4 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 5 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 6 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 7 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 8 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 9 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 10 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 11 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 12 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 13 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 14 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 15 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 16 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 17 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 18 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres' WHERE `id_producto` = 19 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 20 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 21 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 22 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 23 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 24 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 25 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 26 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 27 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 28 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 29 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 30 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 31 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 32 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 33 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 34 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, deportistas / actividad física, embarazo y lactancia: no recomendado' WHERE `id_producto` = 35 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 36 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'niños' WHERE `id_producto` = 37 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 38 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 39 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 40 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 41 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 42 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 43 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 44 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 45 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'deportistas / actividad física' WHERE `id_producto` = 46 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 47 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 48 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 49 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física, embarazo y lactancia: no recomendado' WHERE `id_producto` = 50 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 51 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 52 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física' WHERE `id_producto` = 53 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 54 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 55 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 56 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 57 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 58 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 59 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 60 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 61 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 62 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 63 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 64 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 65 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 66 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'deportistas / actividad física' WHERE `id_producto` = 67 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'deportistas / actividad física' WHERE `id_producto` = 68 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 69 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 70 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 71 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 72 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'niños' WHERE `id_producto` = 73 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 74 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'niños' WHERE `id_producto` = 75 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 76 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 77 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 78 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 79 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 80 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 81 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 82 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 83 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 84 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 85 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres' WHERE `id_producto` = 86 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 87 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 88 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 89 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 90 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 91 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 92 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 93 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 94 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 95 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 96 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 97 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 98 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 99 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 100 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'niños' WHERE `id_producto` = 101 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 102 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 103 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 104 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 105 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 106 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 107 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 108 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'niños' WHERE `id_producto` = 109 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física, embarazo y lactancia: no recomendado' WHERE `id_producto` = 110 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 111 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, deportistas / actividad física' WHERE `id_producto` = 112 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres' WHERE `id_producto` = 113 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, adultos mayores' WHERE `id_producto` = 114 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres' WHERE `id_producto` = 115 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, deportistas / actividad física' WHERE `id_producto` = 116 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres' WHERE `id_producto` = 117 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 118 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 119 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 120 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 121 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 122 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 123 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 124 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 125 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 126 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 127 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 128 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 129 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 130 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 131 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 132 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 133 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 134 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 135 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 136 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 137 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 138 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 139 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 140 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 141 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 142 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 143 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 144 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 145 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 146 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 147 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 148 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 149 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física, embarazo y lactancia: no recomendado' WHERE `id_producto` = 150 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, apoyo durante el embarazo (consultar a un profesional de salud antes de usar)' WHERE `id_producto` = 151 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, adultos mayores' WHERE `id_producto` = 152 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, adultos mayores' WHERE `id_producto` = 153 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 154 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física, embarazo y lactancia: no recomendado' WHERE `id_producto` = 155 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 156 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 157 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 158 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física' WHERE `id_producto` = 159 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 160 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 161 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física' WHERE `id_producto` = 162 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 163 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 164 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 165 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 166 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 167 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 168 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 169 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 170 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 171 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 172 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 173 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 174 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 175 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres' WHERE `id_producto` = 176 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, deportistas / actividad física' WHERE `id_producto` = 177 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 178 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física, embarazo y lactancia: no recomendado' WHERE `id_producto` = 179 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 180 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 181 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 182 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 183 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 184 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, adultos mayores' WHERE `id_producto` = 185 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres' WHERE `id_producto` = 186 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, adultos mayores' WHERE `id_producto` = 187 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 188 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 189 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 190 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 191 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 192 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 193 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 194 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 195 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'niños' WHERE `id_producto` = 196 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 201 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'deportistas / actividad física' WHERE `id_producto` = 206 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 209 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'deportistas / actividad física' WHERE `id_producto` = 211 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 214 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 215 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 216 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 217 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 218 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física' WHERE `id_producto` = 219 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores, embarazo y lactancia: no recomendado' WHERE `id_producto` = 222 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 223 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 224 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 225 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física' WHERE `id_producto` = 226 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, adultos mayores' WHERE `id_producto` = 227 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 228 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 229 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 230 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 231 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, deportistas / actividad física' WHERE `id_producto` = 232 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 233 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 234 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 235 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres' WHERE `id_producto` = 236 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 237 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 238 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 239 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 240 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 241 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 242 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 243 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, embarazo y lactancia: no recomendado' WHERE `id_producto` = 244 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres' WHERE `id_producto` = 245 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mujeres y hombres, deportistas / actividad física, embarazo y lactancia: no recomendado' WHERE `id_producto` = 247 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'hombres, adultos mayores' WHERE `id_producto` = 249 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
UPDATE `productos` SET `perfil_recomendado` = 'mascotas (perros y gatos)' WHERE `id_producto` = 252 AND (`perfil_recomendado` IS NULL OR `perfil_recomendado` = '');
