-- Migracion: puebla_producto_relacionados_venta_cruzada. Idempotente (INSERT IGNORE +
-- UNIQUE KEY en (id_producto, id_producto_relacionado)).
--
-- Relaciones de venta cruzada redactadas a mano (sin DeepSeek) agrupando el catalogo en
-- clusters tematicos (magnesio, colageno, probioticos, omega, hombre/mujer/ninos,
-- cosmeticos, deportistas, mascotas, etc.) y asignando 1-2 "anclas" de venta cruzada por
-- cluster. Es un insumo interno para el vendedor/encargado y Alex -- no se muestra tal
-- cual al cliente, es para orientar que segundo producto ofrecer.

INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (5, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (5, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (8, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (8, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (28, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (28, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (29, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (29, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (33, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (33, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (55, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (55, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (56, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (56, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (57, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (57, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (58, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (58, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (59, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (59, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (89, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (89, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (90, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (90, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (110, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (110, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (110, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (111, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (111, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (174, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (174, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (174, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (174, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (209, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (209, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (222, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (222, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (225, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (225, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (244, 69, 'el magnesio ayuda a la absorcion de la vitamina D3');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (244, 44, 'combo clasico para relajacion y manejo del estres');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (63, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (63, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (201, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (201, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (216, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (216, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (218, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (218, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (227, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (227, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (229, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (229, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (230, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (230, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (113, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (113, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (186, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (186, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (186, 51, 'calcio y vitamina D3, combo clasico salud osea 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (186, 63, 'colageno complementa el multivitaminico para mujer');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (24, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (24, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (171, 61, 'la vitamina C favorece la sintesis de colageno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (171, 183, 'biotina complementa el cuidado de piel, cabello y unas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (30, 154, 'fibra + probiotico: combo completo para salud digestiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (30, 78, 'enzimas digestivas complementan el equilibrio de la flora intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (27, 154, 'fibra + probiotico: combo completo para salud digestiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (27, 78, 'enzimas digestivas complementan el equilibrio de la flora intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (32, 154, 'fibra + probiotico: combo completo para salud digestiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (32, 78, 'enzimas digestivas complementan el equilibrio de la flora intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (31, 154, 'fibra + probiotico: combo completo para salud digestiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (31, 78, 'enzimas digestivas complementan el equilibrio de la flora intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (23, 154, 'fibra + probiotico: combo completo para salud digestiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (23, 78, 'enzimas digestivas complementan el equilibrio de la flora intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (18, 154, 'fibra + probiotico: combo completo para salud digestiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (18, 78, 'enzimas digestivas complementan el equilibrio de la flora intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (101, 154, 'fibra + probiotico: combo completo para salud digestiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (101, 78, 'enzimas digestivas complementan el equilibrio de la flora intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (101, 196, 'omega 3 infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (134, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (134, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (135, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (135, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (136, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (136, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (137, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (137, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (138, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (138, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (139, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (139, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (95, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (95, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (193, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (193, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (194, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (194, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (195, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (195, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (223, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (223, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (224, 69, 'omega 3 + vitamina D3, combo comun para bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (224, 157, 'combo antiinflamatorio omega + curcumina');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (85, 113, 'complementa con cuidado del cabello para hombre');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (85, 152, 'combo para hombres 40+: vitalidad + bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (115, 113, 'complementa con cuidado del cabello para hombre');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (115, 152, 'combo para hombres 40+: vitalidad + bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (116, 113, 'complementa con cuidado del cabello para hombre');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (116, 152, 'combo para hombres 40+: vitalidad + bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (176, 113, 'complementa con cuidado del cabello para hombre');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (176, 152, 'combo para hombres 40+: vitalidad + bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (177, 113, 'complementa con cuidado del cabello para hombre');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (177, 152, 'combo para hombres 40+: vitalidad + bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (232, 113, 'complementa con cuidado del cabello para hombre');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (232, 152, 'combo para hombres 40+: vitalidad + bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (112, 113, 'complementa con cuidado del cabello para hombre');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (112, 152, 'combo para hombres 40+: vitalidad + bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (152, 134, 'omega 3 como parte de un combo de bienestar general 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (152, 189, 'zinc complementa el bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (153, 134, 'omega 3 como parte de un combo de bienestar general 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (153, 189, 'zinc complementa el bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (249, 134, 'omega 3 como parte de un combo de bienestar general 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (249, 189, 'zinc complementa el bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (114, 134, 'omega 3 como parte de un combo de bienestar general 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (114, 189, 'zinc complementa el bienestar prostatico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (84, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (84, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (97, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (97, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (121, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (121, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (122, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (122, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (123, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (123, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (124, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (124, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (125, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (125, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (214, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (214, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (161, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (161, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (188, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (188, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (74, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (74, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (79, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (79, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (6, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (6, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (12, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (12, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (13, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (13, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (17, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (17, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (117, 86, 'acido folico, combo comun en bienestar hormonal femenino');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (117, 89, 'magnesio glicinato para acompañar el equilibrio hormonal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (185, 51, 'calcio y vitamina D3, combo clasico salud osea 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (185, 63, 'colageno complementa el multivitaminico para mujer');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (187, 51, 'calcio y vitamina D3, combo clasico salud osea 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (187, 63, 'colageno complementa el multivitaminico para mujer');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (245, 51, 'calcio y vitamina D3, combo clasico salud osea 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (245, 63, 'colageno complementa el multivitaminico para mujer');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (19, 51, 'calcio y vitamina D3, combo clasico salud osea 40+');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (19, 63, 'colageno complementa el multivitaminico para mujer');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (70, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (70, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (71, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (71, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (72, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (72, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (80, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (80, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (81, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (81, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (82, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (82, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (103, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (103, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (132, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (132, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (169, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (169, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (192, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (192, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (234, 63, 'colageno oral complementa la rutina facial topica');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (234, 61, 'vitamina C liposomal como refuerzo antioxidante interno');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (38, 113, 'suplemento capilar para hombre, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (38, 186, 'suplemento capilar para mujer, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (39, 113, 'suplemento capilar para hombre, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (39, 186, 'suplemento capilar para mujer, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (40, 113, 'suplemento capilar para hombre, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (40, 186, 'suplemento capilar para mujer, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (129, 113, 'suplemento capilar para hombre, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (129, 186, 'suplemento capilar para mujer, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (236, 113, 'suplemento capilar para hombre, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (236, 186, 'suplemento capilar para mujer, combo con el cuidado topico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (237, 240, 'prebioticos para mascotas, complementa el bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (238, 237, 'omega para mascotas, combo comun con otros suplementos para mascotas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (238, 240, 'prebioticos para mascotas, complementa el bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (239, 237, 'omega para mascotas, combo comun con otros suplementos para mascotas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (239, 240, 'prebioticos para mascotas, complementa el bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (240, 237, 'omega para mascotas, combo comun con otros suplementos para mascotas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (241, 237, 'omega para mascotas, combo comun con otros suplementos para mascotas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (241, 240, 'prebioticos para mascotas, complementa el bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (242, 237, 'omega para mascotas, combo comun con otros suplementos para mascotas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (242, 240, 'prebioticos para mascotas, complementa el bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (243, 237, 'omega para mascotas, combo comun con otros suplementos para mascotas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (243, 240, 'prebioticos para mascotas, complementa el bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (252, 237, 'omega para mascotas, combo comun con otros suplementos para mascotas');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (252, 240, 'prebioticos para mascotas, complementa el bienestar general');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (46, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (46, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (53, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (53, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (67, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (67, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (68, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (68, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (159, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (155, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (155, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (162, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (162, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (206, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (206, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (211, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (211, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (219, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (219, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (226, 110, 'electrolitos (magnesio + potasio) para acompañar el entrenamiento');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (226, 159, 'glutamina para recuperacion muscular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (96, 69, 'vitamina D3, combo clasico de apoyo inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (96, 189, 'zinc complementa el apoyo al sistema inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (77, 69, 'vitamina D3, combo clasico de apoyo inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (77, 189, 'zinc complementa el apoyo al sistema inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (54, 69, 'vitamina D3, combo clasico de apoyo inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (54, 189, 'zinc complementa el apoyo al sistema inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (61, 69, 'vitamina D3, combo clasico de apoyo inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (61, 189, 'zinc complementa el apoyo al sistema inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (145, 69, 'vitamina D3, combo clasico de apoyo inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (145, 189, 'zinc complementa el apoyo al sistema inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (126, 69, 'vitamina D3, combo clasico de apoyo inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (126, 189, 'zinc complementa el apoyo al sistema inmunologico');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (78, 30, 'probiotico complementa el bienestar digestivo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (78, 154, 'fibra (psyllium) complementa el transito intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (87, 30, 'probiotico complementa el bienestar digestivo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (87, 154, 'fibra (psyllium) complementa el transito intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (154, 30, 'probiotico complementa el bienestar digestivo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (76, 30, 'probiotico complementa el bienestar digestivo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (76, 154, 'fibra (psyllium) complementa el transito intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (191, 30, 'probiotico complementa el bienestar digestivo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (191, 154, 'fibra (psyllium) complementa el transito intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (233, 30, 'probiotico complementa el bienestar digestivo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (233, 154, 'fibra (psyllium) complementa el transito intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (15, 30, 'probiotico complementa el bienestar digestivo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (15, 154, 'fibra (psyllium) complementa el transito intestinal');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (99, 63, 'colageno complementa la salud articular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (99, 134, 'omega 3 por su aporte antiinflamatorio');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (100, 63, 'colageno complementa la salud articular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (100, 134, 'omega 3 por su aporte antiinflamatorio');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (157, 63, 'colageno complementa la salud articular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (157, 134, 'omega 3 por su aporte antiinflamatorio');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (178, 63, 'colageno complementa la salud articular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (178, 134, 'omega 3 por su aporte antiinflamatorio');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (36, 63, 'colageno complementa la salud articular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (36, 134, 'omega 3 por su aporte antiinflamatorio');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (47, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (47, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (181, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (181, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (182, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (182, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (94, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (94, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (166, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (166, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (167, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (167, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (168, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (168, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (65, 134, 'omega 3 complementa el bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (65, 2, 'ajo negro, combo comun para bienestar cardiovascular');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (60, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (60, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (105, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (105, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (142, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (142, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (120, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (120, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (228, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (228, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (11, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (11, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (9, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (9, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (127, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (127, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (128, 134, 'omega 3 (DHA) complementa la funcion cognitiva');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (128, 50, 'combo de energia y enfoque mental');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (37, 101, 'probiotico infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (37, 196, 'omega 3 infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (73, 101, 'probiotico infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (73, 196, 'omega 3 infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (75, 101, 'probiotico infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (75, 196, 'omega 3 infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (109, 101, 'probiotico infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (109, 196, 'omega 3 infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (196, 101, 'probiotico infantil, combo comun en la rutina de los niños');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (92, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (92, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (43, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (140, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (140, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (190, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (48, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (48, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (14, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (14, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (25, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (25, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (26, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (26, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (16, 190, 'picolinato de cromo complementa el manejo de peso y metabolismo');
INSERT IGNORE INTO `producto_relacionados` (`id_producto`, `id_producto_relacionado`, `nota`) VALUES (16, 43, 'vinagre de sidra de manzana, combo clasico de metabolismo');
